

DROP TABLE IF EXISTS crm_roles CASCADE;
DROP TABLE IF EXISTS crm_permissions CASCADE;
DROP TABLE IF EXISTS crm_users CASCADE;
DROP TABLE IF EXISTS crm_images CASCADE;
DROP TABLE IF EXISTS crm_pdf CASCADE;
DROP TABLE IF EXISTS crm_document CASCADE;
DROP TABLE IF EXISTS crm_contacts CASCADE;
DROP TABLE IF EXISTS crm_contact_name CASCADE;
DROP TABLE IF EXISTS crm_phone CASCADE;
DROP TABLE IF EXISTS crm_phone_type CASCADE;
DROP TABLE IF EXISTS crm_contact_class CASCADE;
DROP TABLE IF EXISTS crm_contact_type CASCADE;

