

DROP TABLE IF EXISTS crm_roles CASCADE;
DROP TABLE IF EXISTS crm_permissions CASCADE;
DROP TABLE IF EXISTS crm_users CASCADE;
DROP TABLE IF EXISTS crm_images CASCADE;
DROP TABLE IF EXISTS crm_pdf CASCADE;
DROP TABLE IF EXISTS crm_document CASCADE;
DROP TABLE IF EXISTS crm_contacts CASCADE;
DROP TABLE IF EXISTS crm_contact_name CASCADE;
DROP TABLE IF EXISTS crm_phone CASCADE;
DROP TABLE IF EXISTS crm_phone_type CASCADE;
DROP TABLE IF EXISTS crm_contact_class CASCADE;
DROP TABLE IF EXISTS crm_address CASCADE;
DROP TABLE IF EXISTS crm_email CASCADE;
DROP TABLE IF EXISTS crm_email_types CASCADE;
DROP TABLE IF EXISTS crm_licencee_list CASCADE;
DROP TABLE IF EXISTS crm_social_media CASCADE;
DROP TABLE IF EXISTS crm_client_list CASCADE;
DROP TABLE IF EXISTS crm_products CASCADE;
DROP TABLE IF EXISTS crm_alch_products CASCADE;
DROP TABLE IF EXISTS crm_non_alch_products CASCADE;
DROP TABLE IF EXISTS crm_products_bc_alcoholic CASCADE;
DROP TABLE IF EXISTS crm_alch_classes CASCADE;
DROP TABLE IF EXISTS crm_non_alch_classes CASCADE;
DROP TABLE IF EXISTS crm_contact_type CASCADE;
DROP TABLE IF EXISTS crm_supplier_contact CASCADE;
DROP TABLE IF EXISTS crm_client CASCADE;
DROP TABLE IF EXISTS crm_supplier CASCADE;
DROP TABLE IF EXISTS crm_client_contact CASCADE;
DROP TABLE IF EXISTS crm_sales_rep_assignment CASCADE;
DROP TABLE IF EXISTS crm_products_bc CASCADE;
DROP TABLE IF EXISTS crm_sales_call CASCADE;
DROP TABLE IF EXISTS crm_product_tasting CASCADE;
DROP TABLE IF EXISTS crm_country_code CASCADE;
DROP TABLE IF EXISTS crm_province_state CASCADE;


DROP SEQUENCE crm_images_id_seq;
