



CREATE SEQUENCE crm_images_id_seq START WITH 50;
CREATE SEQUENCE crm_roles_seq START WITH 50;
CREATE SEQUENCE crm_permissions_seq START WITH 50;
CREATE SEQUENCE crm_users_seq START WITH 50;
CREATE SEQUENCE crm_pdf_seq START WITH 50;
CREATE SEQUENCE crm_document_seq START WITH 50;
CREATE SEQUENCE crm_entities_seq START WITH 50;
CREATE SEQUENCE crm_contact_name_seq START WITH 50;
CREATE SEQUENCE crm_phone_seq START WITH 50;
CREATE SEQUENCE crm_phone_type_seq START WITH 50;
CREATE SEQUENCE crm_address_seq START WITH 50;
CREATE SEQUENCE crm_email_seq START WITH 50;
CREATE SEQUENCE crm_email_type_seq START WITH 50;
CREATE SEQUENCE crm_licencee_list_seq START WITH 50;
CREATE SEQUENCE crm_social_media_seq START WITH 50;
CREATE SEQUENCE crm_social_media_type_seq START WITH 50;
CREATE SEQUENCE crm_client_list_seq START WITH 50;
CREATE SEQUENCE crm_products_seq START WITH 50;
CREATE SEQUENCE crm_alch_products_seq START WITH 50;
CREATE SEQUENCE crm_non_alch_products_seq START WITH 50;
CREATE SEQUENCE crm_products_bc_alcoholic_seq START WITH 50;
CREATE SEQUENCE crm_supplier_seq START WITH 50;
CREATE SEQUENCE crm_supplier_type_seq START WITH 50;
CREATE SEQUENCE crm_alch_classes_seq START WITH 50;
CREATE SEQUENCE crm_non_alch_classes_seq START WITH 50;
CREATE SEQUENCE crm_contact_class_seq START WITH 50;
CREATE SEQUENCE crm_entity_class_seq START WITH 50;
CREATE SEQUENCE crm_supplier_contact_seq START WITH 50;
CREATE SEQUENCE crm_client_type_seq START WITH 50;
CREATE SEQUENCE crm_client_seq START WITH 50;
CREATE SEQUENCE crm_client_contact_seq START WITH 50;
CREATE SEQUENCE crm_sales_rep_assignment_seq START WITH 50;
CREATE SEQUENCE crm_products_bc_seq START WITH 50;
CREATE SEQUENCE crm_sales_call_seq START WITH 50;
CREATE SEQUENCE crm_product_tasting_seq START WITH 50;
CREATE SEQUENCE crm_country_code_seq START WITH 100;
CREATE SEQUENCE crm_province_state_seq START WITH 250;


-- CREATE SEQUENCE _seq START WITH 50;
-- CREATE SEQUENCE _seq START WITH 50;
-- CREATE SEQUENCE _seq START WITH 50;
-- CREATE SEQUENCE _seq START WITH 50;
-- CREATE SEQUENCE _seq START WITH 50;
-- CREATE SEQUENCE _seq START WITH 50;
-- CREATE SEQUENCE _seq START WITH 50;
-- CREATE SEQUENCE _seq START WITH 50;
-- CREATE SEQUENCE _seq START WITH 50;
-- CREATE SEQUENCE _seq START WITH 50;
-- CREATE SEQUENCE _seq START WITH 50;
